import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Providers from "./provider";

// TypeScript may not have module declarations for CSS imports in this project setup.
// Ignore the next line so the side-effect import of the global stylesheet doesn't error.
// @ts-ignore
import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

import NavbarWrapper from "@/components/navbar/navWrapper";
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` h-screen overflow-auto   ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          {children}
          {/* FloatingNavbar should be outside of the main content to ensure it overlays correctly */}
          {/** Now check if login or sign in page then none */}
          <NavbarWrapper />
        </Providers>
      </body>
    </html>
  );
}
